### ISSUE TITLE
Przygotowanie node'a meldog-moteus

### ISSUE THREAD

**Issue by pktiuk** [KNR-PW/meldog-ros#2]
Stworzenie node'a wraz z dokumentacją, który będzie wrzucać na topiki informacje z meldoga

**Comment by BartlomiejK2** [comment]
Node do sterowania kilkoma moteusami naraz: 
src/meldog_brigde/meldog_bridge/multi_moteus_controller

Publisher: "multi_moteus_state" - wysyła aktualną listę danych o moteusach (MultiMoteusState)
Subscriber: "multi_moteus_control" - otrzymuje dla każdego moteusa dane (MultiMoteusControl)
Service: "moteus_active_srv" - otrzymuje dane które moteusy mają być aktywne (MultiMoteusActive)


Nowa paczka dla autorskich interface'ów do meldoga:
src/meldog_interfaces

msg:

- MultiMoteusState:
    MoteusState [ ] state_array

- MultiMoteusControl:
    MoteusControl [ ] control_array

- MoteusState:
    float32 position
    float32 velocity
    float32 torque
    float32 q_current
    float32 d_current
    float32 q_current

- MoteusControl:
    float32 desired_position
    float32 desired_velocity
    float32 feedforward_torque

srv:

- MultiMoteusActive:
    bool [ ] active

    ---
    bool [ ] success

**Comment by pktiuk** [comment]
Nie muszą to być konkretnie wiadomości moteusowe.   
Poszukałbym raczej jakichś uniwersalnych formatów wiadomości niezwiązanych z żadnym producentem.    
No chyba, że moteus to jest nazwa standardu przemysłowego, a nie marki.
